### ISSUE TITLE
MathColor doesn't seem to work

### ISSUE THREAD

**Issue by Jacobgarm** [file-acomplaint/GodoTeX#2]
Platform: Linux
Godot version: 3.5.0

The texture of any LaTeX node is always black irrespective of the MathColor variable. This is true for both LaTeX and LaTexButton.

What i have tried:
- Changing the Math Color property in the inspector
- Change the color in a script
- Changing the Modulate and Self Modulate options
- Using the included sample scene

Image showing wrongly colored LaTeX nodes:
![image](https://user-images.githubusercontent.com/37753339/188710009-cb15d200-666c-4bee-ab1d-374df9b5db52.png)

**Comment by Jacobgarm** [comment]
Nevermind, turns a out the version on the Godot asset store is not the most recent version. Closing issue

**Comment by file-acomplaint** [comment]
Exactly right. Sorry for the inconvenience, I'll update the asset story entry soon!
