### ISSUE TITLE
Include CSharpMath instruction aren't clear for beginners

### ISSUE THREAD

**Issue by iRadEntertainment** [file-acomplaint/GodoTeX#3]
The "how to instructions" states that you can include CSharpMath in your Godot project by adding the ItemTags found in GodoTeX.csproj to the project.csproj.

This isn't sufficient as the plugin cannot start.
Can you expand the info on how to properly include the CSharpMath as a nugget into the Godot project more clearly?

I am personally at my beginning with C# in Godot, so most things are new to me.

**Comment by file-acomplaint** [comment]
Hi, thanks for trying out GodoTeX!

I don't know what you did, so I can only vaguely guess what went wrong. Did you maybe get some sort of error message that you can share?
In any case, just editing the .csproj file will tell the compiler to install the dependencies, not install the plugin. That is what steps 1, 2 and 4 in the instructions are for.

**Comment by iRadEntertainment** [comment]
Sorry, I think it was my fault somehow. Adding the `<ItemGroup>` tags was enough to include the library. I manage to make it run in the editor. So I think the instruction will suffice! I'm closing this issue.

**Comment by file-acomplaint** [comment]
Nice, I'm glad you got it to work!
